#!/usr/bin/env ruby
require 'keychain'
require 'clipboard'
require 'rotp'
require 'wikk_configuration'

# Read back the default google authenticator key from the Mac OS X keychain.
#  (Will get prompted for the users password to access the keychain.)
# The default is stored in the users home directory in .gauth.
# Generate the next 2FA key, and put it in the Mac OS X clipboard.

conf = WIKK::Configuration.new(File.expand_path('~/.gauth'))
Keychain.generic_passwords.where(service: 'Google_Authenticator', account: conf.account, label: conf.label).all.each do |p|
  totp = ROTP::TOTP.new( p.password )
  result = totp.now
  Clipboard.copy result
  puts "#{p.label}:#{p.account}: #{result}"
end
