#!/usr/bin/env ruby
require 'keychain'

# Store a google authentication key in the Mac OS X keychain.
# Provide the provider name, account at that provider, and the rotp password as arguments.
#  Will get prompted for local account password by Mac OS X to access the keychain.

if ARGC != 3
  puts 'Usage: gauth_config provider account key'
  exit 1
end
begin
  issuer = ARGV[0]
  issuer = issuer.split('@')[1] if issuer =~ /@/      # Set issuer to the domain part, if it is in the form user@domain style
  account = "#{ARGV[1].gsub(/@.*$/, '')}@#{issuer}"                    # Set Account to account@issuer, which should be unique.

  Keychain.generic_passwords.create(service: 'Google_Authenticator',
                                    password: ARGV[2],
                                    account: account,
                                    label: issuer
                                   )
rescue Excepton => e
  puts "Failed to create keychain entry: #{e}"
end
